version: '3'

services:
  infrack:
    image: bproenca/db-ins:jvm17azul
    restart: always
    ports:
      - "8181:8080"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 70M
    environment:
      - JAVA_OPTS=-Xmx50M
      - SPRING_DATASOURCE_URL=<url>
      - SPRING_DATASOURCE_USERNAME=<user>
      - SPRING_DATASOURCE_PASSWORD=<pass>
      - APP_TIME_DB=60000